language: go

go:
  - "1.x"

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_install:
  - go get -v golang.org/x/net/proxy

script:
  - go build ./...

after_success:
  - export CODECOV_TOKEN="34dfb5a9-348d-4742-861d-cab5505b3d25"
  - bash <(curl -s https://codecov.io/bash)

